project:
  type: book
  output-dir: docs

execute:
  echo: false
  warning: false
  message: false

toc: true
toc-depth: 3
# bibliography: references.bib

book:
  title: "Project Notebook for RISK"
  author:
  - John J. Curtin
  - Claire Punturieri
  - Coco Yu
  - Kendra Wyant
  - Susan Wanta
  - Gaylen Fronk
  site-url: https://github.io/jjcurtin/docs_risk
  repo-url: https://github.com/jjcurtin/docs_risk
  repo-branch: main
  repo-actions: [edit]
  sharing: [facebook, linkedin]
  page-navigation: true
  chapters:
    - index.qmd
    - part: "Overview"
      chapters:
        - study_procedure.qmd
        - study_recruitment.qmd
        - study_visits.qmd
        - completed_manuscripts.qmd
    - part: "Studies"
      chapters:
        - study_gps.qmd
        - study_messages.qmd
        - study_insight.qmd

